//
//   Paradigm Perspective
//   Tanner Wright
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Scripts.Game
{
	public class Game
	{
		public static float GravityStrength = 60.0f;
		public static float playerTerminalVelocity = 12.0f;
		public static float playerBrakingRate = 10.0f;
	}
}

