//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
namespace Scripts.Pyramid
{
		public class Gravity : MonoBehaviour
		{
				public static List<GameObject> gravityList = new List<GameObject> ();
				
				public static void addObjectToGravityList (GameObject go)
				{
						gravityList.Add (go);
				}
				
				public void Update ()
				{
						foreach (GameObject go in gravityList) {
					
						}
				}
		}
}

